.TH root 1
.SH NAME
root \- run a command as the root user
.SH SYNOPSIS
root
.I command
.RI [ argument ]...
.SH DESCRIPTION
.B root
runs
.I command
as the root user, but with the current user's environment.
.P
It is a designed as a simpler, more predictable alternative to
.BR sudo ,
which sometimes changes environment variables such as
.BR PATH .
.SH OPTIONS
None.
.SH ENVIRONMENT
A user must be in group 0 to run the command, which is usually
.B root
or
.BR wheel .
.P
You can run
.B "root id -gn"
to confirm which.
.SH BUGS
.B root \-\-
should do the same thing as
.BR root ,
but doesn't yet.
.SH AUTHOR
Mikel Ward <mikel@mikelward.com>
.SH "SEE ALSO"
.BR sudo (1)
.BR id (1)
