.TH root 1
.SH NAME
root \- run a command as the root user
.SH SYNOPSIS
root
.I command
.RI [ argument ]...
.SH DESCRIPTION
.B root
runs
.I command
as the root user, but with the current user's environment.
.P
It is a designed as a more predictable alternative to
.BR sudo ,
which sometimes changes
.BR PATH .
.SS Permission to run root
A user must be in group 0 to run a command using
.BR root .
.P
Group 0 is usually
.B root
or
.BR wheel .
You can run
.B "root id -gn"
to confirm the correct group name.
.P
To grant
.I user
permission to run
.BR root ,
run:
.P
.RS
.B su -
.RE
.RS
.B gpasswd -a
.I user
.B $(root id -gn)
.RE
.P
.SS Relative Paths
.B root
will not run any command found via "", ".", or any other relative directory path appearing in
.IR PATH .
.P
This is a security precaution to prevent running files that could be malicious, for example
.P
.RS
.B root ls
.RE
.P
could run /tmp/ls rather than /bin/ls if somebody created /tmp/ls and it was run in the /tmp directory.
.P
Specifying
.I command
as an absolute path is recommended, e.g.
.P
.RS
.B root /bin/ls

.SS "Shell Aliases"
For shell aliases to work as expected, you should add:
.P
.RS
.B alias root='root '
.P
.RE
to your shell configuration file.
.SH BUGS
.B root \-\-
should do the same thing as
.BR root ,
but doesn't yet.
.P
.SH OPTIONS
None.
.SH AUTHOR
Mikel Ward <mikel@mikelward.com>
.SH "SEE ALSO"
.BR sudo (1)
.BR id (1)
